server:
  port: 8080
  servlet:
    session:
      timeout: PT1H # session有效时间设置为一小时
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_study?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  session:
    store-type: redis
  thymeleaf:
    cache: false