server:
  port: 8082
  servlet:
    context-path: /web
spring:
  datasource:
    druid:
      # 数据库访问配置
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot_study?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: root
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接超时等待时间
      max-wait: 30000
      # 配置检测可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      # 打开PSCache，并且指定每个连接上的PSCache大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉监控见界面sql无法统计，‘wall’用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如org.shiloh.web.service.*,配置多个则使用,分隔
      aop-patterns: org.shiloh.web.service.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.html,*.css,*.png,*.jpg,*.jpeg,*.gif,*.ico,/druid/*'
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        reset-enable: false
        # druid监控帐号密码
        login-username: root
        login-password: root
      # 配置过滤器
      filter:
        stat:
          log-slow-sql: true
mybatis:
  type-aliases-package: org.shiloh.web.entity
  mapper-locations: classpath:mappers/**/*